## Numpy array and basics 
learn about numpy with me ofc

In [1]:
%pip install numpy
%pip install -U ipykernel

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.7 MB 1.9 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.7 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.7 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.7 MB 2.8 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.7 MB 3.2 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.7 MB 3.7 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.7 MB 4.0 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.7 MB 4.2 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.7 MB 4.3 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.7 MB 4.6 MB/s eta 0:00:01
   ----------------


[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

#### creating arr from list

In [9]:
arr_1d = np.array([1, 2, 3])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


#### List vs numpy arr

In [ ]:
py_lsit=[1, 2, 3]
print("Python List mul:", py_lsit*5)

np_arr= np.array([1, 2, 3])#elesment wise multiplication
print("Numpy Array mul:", np_arr*3) #3 here is the scalar multiplier
# -----------------------------------------------


import time # ⏱️ Used to measure execution time
# -----------------------------------------------
# Regular Python list operation
start = time.time() # 🕒 Record the start time
list=[i*2 for i in range(1000000)] # 📝 List comprehension to create a list of 1 million elements
print("\n list operation time:", time.time() - start) #calculate and print the time taken for the operation

# -----------------------------------------------
# NumPy array operation (same task, but faster)
start = time.time() # 🕒 Record start time again
# Create a NumPy array from 0 to 999999 and multiply entire array by 2
np_arr = np.arange(1000000)*2
# ⏱️ Measure how fast NumPy does the same task
print("Numpy operation time:", time.time() - start)


Python List mul: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
Numpy Array mul: [3 6 9]

 list operation time: 0.10884356498718262
Numpy operation time: 0.009534358978271484


##### creating array from scratch

In [24]:
zeros = np.zeros((3, 4))  # Create a 3x4 array filled with zeros
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))    # Create a 2x3 array filled with ones
print("Ones Array:\n", ones)

full = np.full((2, 2), 7)  # Create a 2x2 array filled with the number 7
print("Full Array:\n", full)

random = np.random.random((2, 3))  # Create a 2x2 array with random floats between 0 and 1
print("Random Array:\n", random)

sequence = np.arange(0,11,2)  # Create a sequence of numbers from 0 to 9
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.07811504 0.52406703 0.54787676]
 [0.70704233 0.99386449 0.82584451]]
Sequence Array:
 [ 0  2  4  6  8 10]


#### Vector, Matrix and Tensor

In [32]:
vector = np.array([1, 2, 3])  # Create a vector (1D array)
vector = vector * 2  # Multiply each element of the vector by 2
print("Vector Array:", vector)


matrix = np.array([[1, 2], 
                   [3, 4]])  # Create a 2D array (matrix)
matrix = matrix + 5  # Add 5 to each element of the matrix
print('matrix: ',matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Create a 3D array (tensor)
print("Tensor Array:\n", tensor)

Vector Array: [2 4 6]
matrix:  [[6 7]
 [8 9]]
Tensor Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### arr properties

In [34]:
arr = np.array([[1, 2, 3],
               [4,5,6]])  # Create a 2D 

print('shape of arr:', arr.shape)  # Print the shape of the array
print('size of arr:', arr.size)  # Print the size of the array
print('dimensions of arr:', arr.ndim)  # Print the number of dimensions of the array
print('dtype of arr:', arr.dtype)  # Print the data type of the array

shape of arr: (2, 3)
size of arr: 6
dimensions of arr: 2
dtype of arr: int64


#### Arr reshaping

In [40]:
arr = np.arange(12)
print('og arr:', arr)

arr = arr.reshape(3, 4)  # Reshape the array to 3 rows and 4 columns
print('\nreshaped arr:', arr)

flattend_arr = arr.flatten()  # Flatten the array to 1D
print('\nflattend arr:', flattend_arr)

#ravel returns a flattened array, but it does not create a copy if the original array is contiguous in memory
raveled_arr = arr.ravel()  # Ravel the array to 1D (similar to flatten) 
print('\nraveled arr:', raveled_arr)


#Transpose the array (swap rows and columns)
transposed_arr = arr.T  # Transpose the array
print('\ntransposed arr:\n', transposed_arr)


'''
TL;DR (Quick Pick):
Use flatten() when you want to keep the original safe.

Use ravel() when you're optimizing and don’t care about modifying the original.

'''

og arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped arr: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattend arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

transposed arr:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


"\nTL;DR (Quick Pick):\nUse flatten() when you want to keep the original safe.\n\nUse ravel() when you're optimizing and don’t care about modifying the original.\n\n"